export const Questions = [
     
    {
      prompt: "Which of these is not a programming language?",
      optionA: "Python",
      optionB: "JavaScript",
      optionC: "MC-03",
      optionD: "Java",
      answer: "C",
    },
    {
      prompt: "Which of these is not a JavaScript framework?",
      optionA: "React",
      optionB: "Angular",
      optionC: "Vue",
      optionD: "Java",
      answer: "D",
    },
    {
      prompt: "Which company developed the JavaScript language?",
      optionA: "Google",
      optionB: "Microsoft",
      optionC: "Netscape",
      optionD: "Apple",
      answer: "C",
    },
    {
      prompt: "Which of these is a database management system?",
      optionA: "React",
      optionB: "MongoDB",
      optionC: "Django",
      optionD: "Flask",
      answer: "B",
    },
    {
      prompt: "Which of these is a version control system?",
      optionA: "Git",
      optionB: "Linux",
      optionC: "Apache",
      optionD: "Docker",
      answer: "A",
    },
    {
      prompt: "HTML stands for?",
      optionA: "HyperText Markup Language",
      optionB: "HyperLoop Machine Language",
      optionC: "HyperText Machine Language",
      optionD: "HyperTerminal Markup Language",
      answer: "A",
    },
    {
      prompt: "Which of these is used to style a webpage?",
      optionA: "HTML",
      optionB: "CSS",
      optionC: "Python",
      optionD: "SQL",
      answer: "B",
    },
    {
      prompt: "Which of these is a backend language?",
      optionA: "React",
      optionB: "Node.js",
      optionC: "Angular",
      optionD: "Vue",
      answer: "B",
    },
    {
      prompt: "Which HTTP method is used to retrieve data?",
      optionA: "POST",
      optionB: "PUT",
      optionC: "DELETE",
      optionD: "GET",
      answer: "D",
    },
  ];
  